name: Release to Test PyPI

on:
  workflow_run:
    workflows: [build]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && startsWith(github.event.workflow_run.head_commit.message, 'chore(release):') }}
    environment:
      name: Release
      url: https://test.pypi.org/p/py-hello-world-keatincf
    permissions:
      id-token: write
    steps:
      - name: Debug
        run: |
          echo ${{ github.event.workflow_run.conclusion}}
          echo ${{ github.event.workflow_run.head_commit.message }}
          echo ${{ startsWith(github.event.workflow_run.head_commit.message, 'chore(release):') }}
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: python-package-distributions
          github_token: ${{ secrets.RELEASE_TOKEN }}
          path: dist/

